using Microsoft.VisualStudio.Language.Intellisense;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

/* This code was generated by a tool. */

namespace ChASM.Globalz
{
    internal class Specialz
    {
        internal static HashSet<string> Items = new HashSet<string>()
        {
            "rdfsbase",
            "rdgsbase",
            "syscall",
            "int",
            "call"
        };

        internal static HashSet<Completion> CodeSamples = new HashSet<Completion>()
        {
            new Completion("pasteHelloWorldHere();",
@"extrn MessageBoxA : proc

.data
szText db ""Welcome to the World of Windows x64 Assembly"", 0

.code
Main proc

    sub rsp, 28h
    xor r9, r9
    lea r8, szText
    lea rdx, szText
    xor rcx, rcx
    call MessageBoxA ;say hello
    add rsp, 28h
	
    ret
Main endp
end",
                "Paste Hello World program code here.",
                CodeCompletion.GetItemIcon(CompletionItemType.CodeSample), null)
        };
    }
}
